# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: evidentia.net
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5


# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:

  - Name: Requester
    Domain: requester.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: ImmigrationDepartment
    Domain: ind.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Coordinator
    Domain: coord.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: University
    Domain: uni.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Bank
    Domain: bank.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Employer
    Domain: employer.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: BorderControl
    Domain: bc.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: Police
    Domain: police.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1

  - Name: MedicalAssociation
    Domain: medicine.evidentia.net
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
