# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.evidentia.net:
  peer0.requester.evidentia.net:
  peer1.requester.evidentia.net:
  peer0.ind.evidentia.net:
  peer1.ind.evidentia.net:
  peer0.coord.evidentia.net:
  peer1.coord.evidentia.net:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-requester
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.requester.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.requester.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin_requester:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/requester.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ind
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ind.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ind.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin_ind:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ind.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coord
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.coord.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.coord.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin_coord:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/coord.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg3
    networks:
      - byfn

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-uni
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.uni.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.uni.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA4_PRIVATE_KEY -b admin_uni:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/uni.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg4
    networks:
      - byfn

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA5_PRIVATE_KEY
    ports:
      - "11054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bank.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA5_PRIVATE_KEY -b admin_bank:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bank.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg5
    networks:
      - byfn

  ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-employer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.employer.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA6_PRIVATE_KEY
    ports:
      - "12054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.employer.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA6_PRIVATE_KEY -b admin_employer:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/employer.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg6
    networks:
      - byfn

  ca6:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bc
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bc.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA7_PRIVATE_KEY
    ports:
      - "13054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bc.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA7_PRIVATE_KEY -b admin_bc:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bc.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg7
    networks:
      - byfn

  ca7:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-police
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.police.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA8_PRIVATE_KEY
    ports:
      - "14054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.police.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA8_PRIVATE_KEY -b admin_police:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/police.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg8
    networks:
      - byfn


  ca8:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-medicine
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.medicine.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA9_PRIVATE_KEY
    ports:
      - "15054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.medicine.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA9_PRIVATE_KEY -b admin_medicine:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/medicine.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg9
    networks:
      - byfn


  orderer.evidentia.net:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.evidentia.net
    container_name: orderer.evidentia.net
    networks:
      - byfn

  peer0.requester.evidentia.net:
    container_name: peer0.requester.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.requester.evidentia.net
    networks:
      - byfn

  peer1.requester.evidentia.net:
    container_name: peer1.requester.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.requester.evidentia.net
    networks:
      - byfn

  peer0.ind.evidentia.net:
    container_name: peer0.ind.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.ind.evidentia.net
    networks:
      - byfn

  peer1.ind.evidentia.net:
    container_name: peer1.ind.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.ind.evidentia.net
    networks:
      - byfn

  peer0.coord.evidentia.net:
    container_name: peer0.coord.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.coord.evidentia.net
    networks:
      - byfn

  peer1.coord.evidentia.net:
    container_name: peer1.coord.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.coord.evidentia.net
    networks:
      - byfn

  peer0.uni.evidentia.net:
    container_name: peer0.uni.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.uni.evidentia.net
    networks:
      - byfn

  peer1.uni.evidentia.net:
    container_name: peer1.uni.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.uni.evidentia.net
    networks:
      - byfn

  peer0.bank.evidentia.net:
    container_name: peer0.bank.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank.evidentia.net
    networks:
      - byfn

  peer1.bank.evidentia.net:
    container_name: peer1.bank.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bank.evidentia.net
    networks:
      - byfn

  peer0.employer.evidentia.net:
    container_name: peer0.employer.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.employer.evidentia.net
    networks:
      - byfn

  peer1.employer.evidentia.net:
    container_name: peer1.employer.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.employer.evidentia.net
    networks:
      - byfn

  peer0.bc.evidentia.net:
    container_name: peer0.bc.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bc.evidentia.net
    networks:
      - byfn

  peer1.bc.evidentia.net:
    container_name: peer1.bc.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bc.evidentia.net
    networks:
      - byfn

  peer0.police.evidentia.net:
    container_name: peer0.police.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.police.evidentia.net
    networks:
      - byfn

  peer1.police.evidentia.net:
    container_name: peer1.police.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.police.evidentia.net
    networks:
      - byfn

  peer0.medicine.evidentia.net:
    container_name: peer0.medicine.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.medicine.evidentia.net
    networks:
      - byfn

  peer1.medicine.evidentia.net:
    container_name: peer1.medicine.evidentia.net
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.medicine.evidentia.net
    networks:
      - byfn
