# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-requester
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.requester.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA1_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.requester.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA1_PRIVATE_KEY} -b admin_requester:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/requester.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-ind
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.ind.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA2_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.ind.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA2_PRIVATE_KEY} -b admin_ind:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/ind.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg2
    networks:
      - byfn

  ca2:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-coord
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.coord.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA3_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=9054
    ports:
      - "9054:9054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.coord.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA3_PRIVATE_KEY} -b admin_coord:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/coord.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
      - ./CoordinatorCA/fabric-ca-server-config.yaml:/etc/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
    container_name: ca_peerOrg3
    networks:
      - byfn

  ca3:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-uni
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.uni.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA4_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=10054
    ports:
      - "10054:10054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.uni.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA4_PRIVATE_KEY} -b admin_uni:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/uni.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg4
    networks:
      - byfn

  ca4:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bank
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bank.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA5_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=11054
    ports:
      - "11054:11054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bank.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA5_PRIVATE_KEY} -b admin_bank:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bank.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg5
    networks:
      - byfn

  ca5:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-employer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.employer.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA6_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=12054
    ports:
      - "12054:12054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.employer.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA6_PRIVATE_KEY} -b admin_employer:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/employer.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg6
    networks:
      - byfn

  ca6:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bc
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bc.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA7_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=13054
    ports:
      - "13054:13054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bc.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA7_PRIVATE_KEY} -b admin_bc:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bc.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg7
    networks:
      - byfn


  ca7:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-police
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.police.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA8_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=14054
    ports:
      - "14054:14054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.police.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA8_PRIVATE_KEY} -b admin_police:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/police.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg8
    networks:
      - byfn

  ca8:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-medicine
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.medicine.evidentia.net-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${BYFN_CA9_PRIVATE_KEY}
      - FABRIC_CA_SERVER_PORT=15054
    ports:
      - "15054:15054"
    command: sh -c 'fabric-ca-server start --cfg.identities.allowremove --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.medicine.evidentia.net-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/${BYFN_CA9_PRIVATE_KEY} -b admin_medicine:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/medicine.evidentia.net/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg9
    networks:
      - byfn
